<a href="https://colab.research.google.com/github/jes-coder/Linear-Algebra---58013/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Problem 1. Consider the four matrices, (20 points each)

import numpy as np

# Define the matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[12], [34], [56]])
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
D = np.array([[12, 34]])

# a. AB
result_a = np.dot(A, B)

# b. D + D
result_b = D + D

# c. 2C
result_c = 2 * C

# Print the results
print("Result of AB:")
print(result_a)

print("\nResult of D + D:")
print(result_b)

print("\nResult of 2C:")
print(result_c)

Result of AB:
[[248]
 [554]]

Result of D + D:
[[24 68]]

Result of 2C:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [3]:
#Problem 2. Find the cross-product of matrices, A = [2,7,4] and
#B = [3,9,8]. Show your solutions using Python program . (40 points)

import numpy as np

# Define the matrices
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

# Calculate the cross product
cross_product = np.cross(A, B)

# result
print("Cross product of A and B: ")
print(cross_product)

Cross product of A and B: 
[20 -4 -3]
