<a href="https://colab.research.google.com/github/jes-coder/Linear-Algebra---58013/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Question 1. (20 points) Create a Multiplication Table/Chart of 1 to 10 using numpy/ python program.

import numpy as np

def multiplication_table(n):
#Create a range of numbers from 1 to n
    numbers = np.arange(1, n+1)

#Create a mesh grid for multiplication
    table = np.meshgrid(numbers, numbers)

#Multiply the elements
    result = table[0] * table[1]

    return result

n = 10

table = multiplication_table(n)
for row in table:
    print(row)


[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[ 3  6  9 12 15 18 21 24 27 30]
[ 4  8 12 16 20 24 28 32 36 40]
[ 5 10 15 20 25 30 35 40 45 50]
[ 6 12 18 24 30 36 42 48 54 60]
[ 7 14 21 28 35 42 49 56 63 70]
[ 8 16 24 32 40 48 56 64 72 80]
[ 9 18 27 36 45 54 63 72 81 90]
[ 10  20  30  40  50  60  70  80  90 100]


In [3]:
#Question 2. (10 points) In relation to Question 1, show a solution that doubles all the values of each element.

import numpy as np

def multiplication_table(n):
#Create a range of numbers from 1 to n
    numbers = np.arange(1, n+1)

#Create a mesh grid for multiplication
    table = np.meshgrid(numbers, numbers)

#Multiply the elements
    result = table[0] * table[1]

#Double all the values
    doubled_result = result * 2

    return doubled_result

n = 10

doubled_table = multiplication_table(n)

for row in doubled_table:
    print(row)


[ 2  4  6  8 10 12 14 16 18 20]
[ 4  8 12 16 20 24 28 32 36 40]
[ 6 12 18 24 30 36 42 48 54 60]
[ 8 16 24 32 40 48 56 64 72 80]
[ 10  20  30  40  50  60  70  80  90 100]
[ 12  24  36  48  60  72  84  96 108 120]
[ 14  28  42  56  70  84  98 112 126 140]
[ 16  32  48  64  80  96 112 128 144 160]
[ 18  36  54  72  90 108 126 144 162 180]
[ 20  40  60  80 100 120 140 160 180 200]


In [5]:
#Question 3. (10 points) Create a square matrix that has a diagonal 1's.

import numpy as np

def create_diagonal_matrix(n):
#Create an n x n matrix with all elements set to 0
    matrix = np.zeros((n, n))

#Set diagonal elements to 1
    np.fill_diagonal(matrix, 1)

    return matrix

n = 5
diagonal_matrix = create_diagonal_matrix(n)
print(diagonal_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
#Question 4. (30 points) Create a matrix whose elements are:
#matrix = np.array([[1, 2, 3, 4],
                   #[5, 6, 7, 8],
                   #[9, 10, 11, 12]])
#Type a python program that can view the size, shape, and dimension of the matrix above.

import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

#size of the matrix
size = matrix.size

#shape of the matrix
shape = matrix.shape

#number of dimensions of the matrix
dimensions = matrix.ndim

print(f"Size of the matrix: {size}")
print(f"Shape of the matrix: {shape}")
print(f"Number of dimensions: {dimensions}")

Size of the matrix: 12
Shape of the matrix: (3, 4)
Number of dimensions: 2


In [9]:
#Question 5. (30 points) Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element.

import numpy as np

arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

#Adding two arrays
result_array = arrayOne + arrayTwo

#Calculate the square of each element in the result array
result_array_squared = np.square(result_array)

#result array
print("Result Array:")
print(result_array)

#result array with squared elements
print("\nResult Array with Squared Elements:")
print(result_array_squared)


Result Array:
[[20 39 33]
 [25 25 28]]

Result Array with Squared Elements:
[[ 400 1521 1089]
 [ 625  625  784]]
