<a href="https://colab.research.google.com/github/jes-coder/Linear-Algebra---58013/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# "Matrix Algebra"

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)



3.0000000000000004

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

In [1]:
# Associative Property (AB)C = A(BC)v

import numpy as np

# Define matrices A, B, and C
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

# Calculate (AB)C and A(BC)
AB_C = np.dot(np.dot(A, B), C)
A_BC = np.dot(A, np.dot(B, C))

# Compare the results
print("Result of (AB)C:")
print(AB_C)

print("\nResult of A(BC):")
print(A_BC)

# Compare if (AB)C is equal to A(BC)
print("\nAre (AB)C and A(BC) equal?", np.array_equal(AB_C, A_BC))


Result of (AB)C:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Result of A(BC):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Are (AB)C and A(BC) equal? True


In [2]:
# Distributive Property 1 A(B + C) = AB + AC

import numpy as np

# Define matrices A, B, and C
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

# Calculate B + C
B_plus_C = B + C

# Calculate A(B + C), AB, and AC
AB_plus_AC = np.dot(A, B_plus_C)
AB_plus_AC_separate = np.dot(A, B) + np.dot(A, C)

# Compare the results
print("Result of A(B + C):")
print(AB_plus_AC)

print("\nResult of AB + AC:")
print(AB_plus_AC_separate)

# Compare if A(B + C) is equal to AB + AC
print("\nAre A(B + C) and AB + AC equal?", np.array_equal(AB_plus_AC, AB_plus_AC_separate))


Result of A(B + C):
[[ 31  26  21]
 [ 88  74  60]
 [145 122  99]]

Result of AB + AC:
[[ 31  26  21]
 [ 88  74  60]
 [145 122  99]]

Are A(B + C) and AB + AC equal? True


In [3]:
# Distributive Property 2 (A + B)C = AC + BC

import numpy as np

# Define matrices A, B, and C
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

# Calculate A + B
A_plus_B = A + B

# Calculate (A + B)C, AC, and BC
A_plus_B_C = np.dot(A_plus_B, C)
AC_plus_BC = np.dot(A, C) + np.dot(B, C)

# Compare the results
print("Result of (A + B)C:")
print(A_plus_B_C)

print("\nResult of AC + BC:")
print(AC_plus_BC)

# Compare if (A + B)C is equal to AC + BC
print("\nAre (A + B)C and AC + BC equal?", np.array_equal(A_plus_B_C, AC_plus_BC))


Result of (A + B)C:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Result of AC + BC:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Are (A + B)C and AC + BC equal? True


In [4]:
# Identity Property IA = A and AI = A (where I is the identity matrix)

import numpy as np

# Define a matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Create an identity matrix with the same shape as A
I = np.eye(A.shape[0])

# Calculate IA and AI
IA = np.dot(I, A)
AI = np.dot(A, I)

# Compare the results
print("Result of IA:")
print(IA)

print("\nResult of AI:")
print(AI)

# Compare if IA and AI are equal to A
print("\nIs IA equal to A?", np.array_equal(IA, A))
print("Is AI equal to A?", np.array_equal(AI, A))


Result of IA:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Result of AI:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Is IA equal to A? True
Is AI equal to A? True


In [5]:
# Zero Property 0A = 0 (where 0 is the zero matrix)

import numpy as np

# Define a matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Create a zero matrix with the same shape as A
zero_matrix = np.zeros(A.shape)

# Calculate 0A
zeroA = np.dot(zero_matrix, A)

# Verify if the result is a zero matrix
print("Result of 0A:")
print(zeroA)


Result of 0A:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Scalar Multiplication Property c(AB) = (cA)B = A(cB)

import numpy as np

# Define matrices A and B, and a scalar constant c
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

c = 2

# Calculate c(AB), (cA)B, and A(cB)
cAB = c * np.dot(A, B)
cA_B = np.dot(c * A, B)
A_cB = np.dot(A, c * B)

# Compare the results
print("Result of c(AB):")
print(cAB)

print("\nResult of (cA)B:")
print(cA_B)

print("\nResult of A(cB):")
print(A_cB)

# Compare if c(AB), (cA)B, and A(cB) are equal
print("\nAre c(AB), (cA)B, and A(cB) equal?",
      np.array_equal(cAB, cA_B) and np.array_equal(cAB, A_cB))


Result of c(AB):
[[ 60  48  36]
 [168 138 108]
 [276 228 180]]

Result of (cA)B:
[[ 60  48  36]
 [168 138 108]
 [276 228 180]]

Result of A(cB):
[[ 60  48  36]
 [168 138 108]
 [276 228 180]]

Are c(AB), (cA)B, and A(cB) equal? True
