<a href="https://colab.research.google.com/github/jes-coder/Linear-Algebra---58013/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

X = np.array([
    [1, 1, 1],
    [3, -2, -1],
    [-1, 4, 2]
], dtype=float)

Y = np.array([
    [1],
    [4],
    [-3]
], dtype=float)

print(X)
print(X.shape)
print(Y)
print(Y.shape)


[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


In [4]:
# Create a python program to solve for the price of flour per sack, yeast per pack, and one piece of egg.

import numpy as np

# Define the coefficient matrix X and the constant vector Y
X = np.array([[30, 10, 120],
              [40, 20, 200],
              [50, 40, 360]], dtype=float)

Y = np.array([12500, 18000, 25700], dtype=float)

# Solve for the prices using NumPy's linear algebra solver
prices = np.linalg.solve(X, Y)

# Extract the prices of flour, yeast, and eggs
flour_price, yeast_price, egg_price = prices

# Print the results
print(f"The price of one sack of flour is {flour_price:.2f} pesos.")
print(f"The price of one pack of yeast is {yeast_price:.2f} pesos.")
print(f"The price of one egg is {egg_price:.2f} pesos.")


The price of one sack of flour is 330.00 pesos.
The price of one pack of yeast is 140.00 pesos.
The price of one egg is 10.00 pesos.
