<a href="https://colab.research.google.com/github/jes-coder/Linear-Algebra---58013/blob/main/Python_Exercise_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# Calculating the Inverse of a Matrix:

import numpy as np
A = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(A)

A = np.array([[1,2],[4,7]])
B = (np.linalg.inv(A))
print(B)

#This code first imports the NumPy library and then defines a matrix A.
#It calculates the inverse of A using np.linalg.inv() and stores it in B.
#Finally, it prints the original matrix A and its inverse B.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-7.  2.]
 [ 4. -1.]]


In [9]:
# Alternate Code for Calculating the Inverse:

import numpy as np
A = np.array([[1,2],[4,7]])
invA = (np.linalg.inv(A))
print(invA)
# This code provides an alternative way to calculate the inverse of matrix A and directly print it.

[[-7.  2.]
 [ 4. -1.]]


In [10]:
# Calculating the Transpose of a Matrix:

A = np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])
print(A)

B = (np.transpose(A))
print(B)

# This code defines a 4x4 matrix A.
# It prints the original matrix A.
# It calculates the transpose of A using np.transpose() and stores it in B.
# Finally, it prints the transposed matrix B.

[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]
[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]
