<a href="https://colab.research.google.com/github/jes-coder/Linear-Algebra---58013/blob/main/Python_Exercise_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

# Declaring matrices
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)

B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

H = np.array([1,2,3,4,5])
describe_mat(H)

#This code will execute all the operations together, defining the describe_mat function
#and then using it to describe the matrices A, G, B, and H. Each matrix will be printed along with its shape and rank.

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1

